### ISSUE TITLE
Add loader for some components

### ISSUE THREAD

**Issue by fernahh** [changelogmeetup/changelogmeetup.github.io#17]
There is a [thirdy lib of loaders](https://github.com/jonjaques/react-loaders) installed on the project and a [Loadr](https://github.com/changelogmeetup/changelogmeetup.github.io/blob/develop/components/loadr.js) component, but thoses things aren't working right now.

### Tasks

- [ ] Add loader to about container
- [ ] Add loader to past events
- [ ] Add loader to Event picture
